/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CostsIndexRouteImport } from './routes/costs/index'
import { Route as EvalsIndexRouteImport } from './routes/evals/index'
import { Route as PromptsIndexRouteImport } from './routes/prompts/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as TracesIndexRouteImport } from './routes/traces/index'
import { Route as TracesTraceIdRouteImport } from './routes/traces/$traceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsIndexRoute = CostsIndexRouteImport.update({
  id: '/costs/',
  path: '/costs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsIndexRoute = EvalsIndexRouteImport.update({
  id: '/evals/',
  path: '/evals/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsIndexRoute = PromptsIndexRouteImport.update({
  id: '/prompts/',
  path: '/prompts/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesIndexRoute = TracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesTraceIdRoute = TracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/costs/': typeof CostsIndexRoute
  '/evals/': typeof EvalsIndexRoute
  '/prompts/': typeof PromptsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/traces/': typeof TracesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/costs': typeof CostsIndexRoute
  '/evals': typeof EvalsIndexRoute
  '/prompts': typeof PromptsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/traces': typeof TracesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/costs/': typeof CostsIndexRoute
  '/evals/': typeof EvalsIndexRoute
  '/prompts/': typeof PromptsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/traces/': typeof TracesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/traces/$traceId'
    | '/costs/'
    | '/evals/'
    | '/prompts/'
    | '/sessions/'
    | '/traces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/traces/$traceId'
    | '/costs'
    | '/evals'
    | '/prompts'
    | '/sessions'
    | '/traces'
  id:
    | '__root__'
    | '/'
    | '/traces/$traceId'
    | '/costs/'
    | '/evals/'
    | '/prompts/'
    | '/sessions/'
    | '/traces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TracesTraceIdRoute: typeof TracesTraceIdRoute
  CostsIndexRoute: typeof CostsIndexRoute
  EvalsIndexRoute: typeof EvalsIndexRoute
  PromptsIndexRoute: typeof PromptsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  TracesIndexRoute: typeof TracesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs/': {
      id: '/costs/'
      path: '/costs'
      fullPath: '/costs/'
      preLoaderRoute: typeof CostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals/': {
      id: '/evals/'
      path: '/evals'
      fullPath: '/evals/'
      preLoaderRoute: typeof EvalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/': {
      id: '/prompts/'
      path: '/prompts'
      fullPath: '/prompts/'
      preLoaderRoute: typeof PromptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/': {
      id: '/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof TracesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/$traceId': {
      id: '/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof TracesTraceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TracesTraceIdRoute: TracesTraceIdRoute,
  CostsIndexRoute: CostsIndexRoute,
  EvalsIndexRoute: EvalsIndexRoute,
  PromptsIndexRoute: PromptsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  TracesIndexRoute: TracesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
