db {
  host: "localhost"
  host: ${?DB_HOST}
  port: 5432
  username: "postgres"
  password: "postgres"
  database: "skunk"
}

lumina {
    worker {
        chunk-size = 100
        poll-interval = 200
    }
}
